# data
data:
  name: 'candi'
  path: '../../Datasets/CANDI'
  crop_x: 160
  crop_y: 176
  crop_z: 144

# network configs
model:
  model_type: 'dit'
  loss_type: 'ncc'
  architecture:
    image_size: [96, 112, 96]
    in_channels: 2
    out_channels: 3
    down_channels: [16, 32, 64, 128, 256]
    use_attention_gates: true
    use_se_attention: true
    decoder_time_embed_dim: 128
    patch_size: 1
    embed_dim: 1152
    depth: 12
    num_heads: 16
    mlp_ratio: 4.

# training configs
training:
  batch_size: 1
  res_levels: 8
  lr: 1e-4
  epochs: 1000
  eval_interval: 1
  checkpoints_path: 'checkpoints/candi_dit.pt'
  logdir: 'logs/candi/candi_dit.log'

# loss factors
loss:
  image_loss_coeff: 1.
  semigroup_coeff: 8e4

# evaluation configs
test:
  down_factor: 2
  save_evals: true
  save_evals_path: 'evals/candi/candi_dit'
  logdir: 'logs/candi/candi_dit_eval.log'
