# data
data:
  name: 'acdc'
  path: '../../Datasets/ACDC'
  crop_x: 128
  crop_y: 128

# network configs
model:
  model_type: 'unet'
  loss_type: 'ncc'
  architecture:
    down_channels: [16, 32, 64, 128, 256]
    up_channels: [256, 128, 64, 32, 16]
    decoder_only: true
    use_attention_gates: true
    use_se_attention: true
    time_emb_dim: 128

# training configs
training:
  batch_size: 1
  res_levels: 8
  lr: 1e-4
  epochs: 500
  eval_interval: 1
  checkpoints_path: 'checkpoints/acdc.pt'
  logdir: 'logs/acdc/acdc.log'

# loss factors
loss:
  image_loss_coeff: 1.
  semigroup_coeff: 3e5

# evaluation configs
test:
  down_factor: 2
  save_evals: true
  save_evals_path: 'evals/acdc/acdc'
  logdir: 'logs/acdc/acdc_eval.log'
