experiment_name: 'lungct_unet_diffeomorphic'

# data
data:
  name: 'lungct'
  path: '../../Datasets/LungCT/'
  crop_x: null
  crop_y: null
  crop_z: null

# network configs
model:
  model_type: 'unet'
  loss_type: 'ngf'
  architecture:
    down_channels: [32, 32, 64, 128]
    up_channels: [128, 64, 32, 32]
    decoder_only: true
    use_attention_gates: true
    use_se_attention: true
    time_emb_dim: 128

# training configs
training:
  batch_size: 1
  res_levels: 8
  lr: 1e-4
  epochs: 400
  eval_interval: 1
  checkpoints_path: 'checkpoints/lungct.pt'
  logdir: 'logs/lungct/lungct.log'

# loss factors
loss:
  image_loss_coeff: 1.
  semigroup_coeff: 1e5

# evaluation configs
test:
  down_factor: 2
  save_evals: true
  save_evals_path: 'evals/lungct/lungct'
  logdir: 'logs/lungct/lungct_eval.log'
