experiment_name: 'mindboggle_unet_deformable'

# data
data:
  name: 'mindboggle'
  path: '../../Datasets/Mindboggle101'
  crop_x: 160
  crop_y: 160
  crop_z: 176

# network configs
model:
  model_type: 'unet'
  loss_type: 'ncc'
  architecture:
    down_channels: [16, 32, 64, 128, 256]
    up_channels: [256, 128, 64, 32, 16]
    decoder_only: true
    use_attention_gates: true
    use_se_attention: true
    time_emb_dim: 128

# training configs
training:
  batch_size: 1
  res_levels: 8
  lr: 1e-4
  epochs: 1000
  eval_interval: 1
  checkpoints_path: 'checkpoints/'
  logdir: 'logs/mindboggle/'

# loss factors
loss:
  image_loss_coeff: 1.
  semigroup_coeff: 1e4

# evaluation configs
test:
  down_factor: 2
  save_evals: true
  save_evals_path: 'evals/mindboggle/'
  logdir: 'logs/mindboggle/'
